/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface FeeRecord {
  'user' : Principal,
  'depositAddress' : string,
  'timestamp' : Time,
  'amount' : bigint,
}
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface LiquidityLock {
  'unlockDate' : Time,
  'duration' : bigint,
  'isLocked' : boolean,
  'amount' : bigint,
}
export interface Memecoin {
  'creator' : Principal,
  'logo' : ExternalBlob,
  'name' : string,
  'createdAt' : Time,
  'liquidityLock' : LiquidityLock,
  'description' : string,
  'totalSupply' : bigint,
  'category' : string,
  'symbol' : string,
}
export interface OwnershipRecord {
  'owner' : Principal,
  'memecoin' : string,
  'amount' : bigint,
  'percentage' : bigint,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface Referral {
  'referralCode' : string,
  'referrer' : Principal,
  'referredUsers' : Array<Principal>,
  'createdAt' : Time,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TradingTransaction {
  'seller' : Principal,
  'timestamp' : Time,
  'buyer' : Principal,
  'memecoin' : string,
  'price' : bigint,
  'amount' : bigint,
}
export interface Transaction {
  'id' : string,
  'status' : TransactionStatus,
  'transactionType' : TransactionType,
  'destinationAddress' : [] | [string],
  'user' : Principal,
  'timestamp' : Time,
  'confirmationDetails' : [] | [string],
  'memecoin' : [] | [string],
  'amount' : bigint,
}
export type TransactionStatus = { 'pending' : null } |
  { 'confirmed' : null } |
  { 'failed' : null };
export type TransactionType = { 'deposit' : null } |
  { 'withdrawal' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'createdAt' : Time,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Wallet {
  'balance' : bigint,
  'owner' : Principal,
  'createdAt' : Time,
  'depositAddress' : string,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'approveTrade' : ActorMethod<[string, Principal, bigint, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createMemecoin' : ActorMethod<
    [string, string, string, bigint, ExternalBlob, bigint, string],
    undefined
  >,
  'designateCEO' : ActorMethod<[Principal], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'generateReferralLink' : ActorMethod<[], string>,
  'getActorId' : ActorMethod<[], string>,
  'getAllOwnershipRecords' : ActorMethod<[], Array<OwnershipRecord>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAllReferrals' : ActorMethod<[], Array<Referral>>,
  'getAllTradingTransactions' : ActorMethod<[], Array<TradingTransaction>>,
  'getAvailableCategories' : ActorMethod<[], Array<string>>,
  'getCEO' : ActorMethod<[], string>,
  'getCEOPrincipal' : ActorMethod<[], [] | [Principal]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerWallet' : ActorMethod<[], [] | [Wallet]>,
  'getDepositAddress' : ActorMethod<[], string>,
  'getFeeRecords' : ActorMethod<[], Array<FeeRecord>>,
  'getHotMemecoins' : ActorMethod<[], Array<Memecoin>>,
  'getIcpswapWalletAddress' : ActorMethod<[], string>,
  'getIcpswapWalletBalance' : ActorMethod<[], bigint>,
  'getIcpswapWalletConnectionStatus' : ActorMethod<[], boolean>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getLiquidityLocks' : ActorMethod<[], Array<LiquidityLock>>,
  'getMemecoins' : ActorMethod<[], Array<Memecoin>>,
  'getMemecoinsbyCategory' : ActorMethod<[string], Array<Memecoin>>,
  'getNewMemecoins' : ActorMethod<[], Array<Memecoin>>,
  'getOfficialDepositAddresses' : ActorMethod<[], Array<string>>,
  'getOfficialTelegram' : ActorMethod<[], string>,
  'getOfficialTwitter' : ActorMethod<[], string>,
  'getOwnershipRecords' : ActorMethod<[], Array<OwnershipRecord>>,
  'getProgressingMemecoins' : ActorMethod<[], Array<Memecoin>>,
  'getReferralCode' : ActorMethod<[], string>,
  'getReferralStats' : ActorMethod<[], [] | [Referral]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTradingFeeRate' : ActorMethod<[], bigint>,
  'getTradingTransactions' : ActorMethod<[], Array<TradingTransaction>>,
  'getTransactionHistory' : ActorMethod<[], Array<Transaction>>,
  'getTrendingMemecoins' : ActorMethod<[], Array<Memecoin>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletConnectionOptions' : ActorMethod<[], Array<[string, boolean]>>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCEO' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'revokeCEO' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setTradingFeeRate' : ActorMethod<[bigint], undefined>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'trackReferral' : ActorMethod<[string], undefined>,
  'tradeMemecoin' : ActorMethod<[string, bigint, bigint, Principal], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'withdrawICP' : ActorMethod<[bigint, string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];