/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const OwnershipRecord = IDL.Record({
  'owner' : IDL.Principal,
  'memecoin' : IDL.Text,
  'amount' : IDL.Nat,
  'percentage' : IDL.Nat,
});
export const Time = IDL.Int;
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const Referral = IDL.Record({
  'referralCode' : IDL.Text,
  'referrer' : IDL.Principal,
  'referredUsers' : IDL.Vec(IDL.Principal),
  'createdAt' : Time,
});
export const TradingTransaction = IDL.Record({
  'seller' : IDL.Principal,
  'timestamp' : Time,
  'buyer' : IDL.Principal,
  'memecoin' : IDL.Text,
  'price' : IDL.Nat,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
});
export const Wallet = IDL.Record({
  'balance' : IDL.Nat,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'depositAddress' : IDL.Text,
});
export const FeeRecord = IDL.Record({
  'user' : IDL.Principal,
  'depositAddress' : IDL.Text,
  'timestamp' : Time,
  'amount' : IDL.Nat,
});
export const LiquidityLock = IDL.Record({
  'unlockDate' : Time,
  'duration' : IDL.Nat,
  'isLocked' : IDL.Bool,
  'amount' : IDL.Nat,
});
export const Memecoin = IDL.Record({
  'creator' : IDL.Principal,
  'logo' : ExternalBlob,
  'name' : IDL.Text,
  'createdAt' : Time,
  'liquidityLock' : LiquidityLock,
  'description' : IDL.Text,
  'totalSupply' : IDL.Nat,
  'category' : IDL.Text,
  'symbol' : IDL.Text,
});
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const TransactionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
  'failed' : IDL.Null,
});
export const TransactionType = IDL.Variant({
  'deposit' : IDL.Null,
  'withdrawal' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'status' : TransactionStatus,
  'transactionType' : TransactionType,
  'destinationAddress' : IDL.Opt(IDL.Text),
  'user' : IDL.Principal,
  'timestamp' : Time,
  'confirmationDetails' : IDL.Opt(IDL.Text),
  'memecoin' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'approveTrade' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createMemecoin' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, ExternalBlob, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'designateCEO' : IDL.Func([IDL.Principal], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'generateReferralLink' : IDL.Func([], [IDL.Text], []),
  'getActorId' : IDL.Func([], [IDL.Text], ['query']),
  'getAllOwnershipRecords' : IDL.Func(
      [],
      [IDL.Vec(OwnershipRecord)],
      ['query'],
    ),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getAllReferrals' : IDL.Func([], [IDL.Vec(Referral)], ['query']),
  'getAllTradingTransactions' : IDL.Func(
      [],
      [IDL.Vec(TradingTransaction)],
      ['query'],
    ),
  'getAvailableCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCEO' : IDL.Func([], [IDL.Text], ['query']),
  'getCEOPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWallet' : IDL.Func([], [IDL.Opt(Wallet)], ['query']),
  'getDepositAddress' : IDL.Func([], [IDL.Text], []),
  'getFeeRecords' : IDL.Func([], [IDL.Vec(FeeRecord)], ['query']),
  'getHotMemecoins' : IDL.Func([], [IDL.Vec(Memecoin)], ['query']),
  'getIcpswapWalletAddress' : IDL.Func([], [IDL.Text], ['query']),
  'getIcpswapWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getIcpswapWalletConnectionStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getLiquidityLocks' : IDL.Func([], [IDL.Vec(LiquidityLock)], ['query']),
  'getMemecoins' : IDL.Func([], [IDL.Vec(Memecoin)], ['query']),
  'getMemecoinsbyCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Memecoin)],
      ['query'],
    ),
  'getNewMemecoins' : IDL.Func([], [IDL.Vec(Memecoin)], ['query']),
  'getOfficialDepositAddresses' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getOfficialTelegram' : IDL.Func([], [IDL.Text], ['query']),
  'getOfficialTwitter' : IDL.Func([], [IDL.Text], ['query']),
  'getOwnershipRecords' : IDL.Func([], [IDL.Vec(OwnershipRecord)], ['query']),
  'getProgressingMemecoins' : IDL.Func([], [IDL.Vec(Memecoin)], ['query']),
  'getReferralCode' : IDL.Func([], [IDL.Text], ['query']),
  'getReferralStats' : IDL.Func([], [IDL.Opt(Referral)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTradingFeeRate' : IDL.Func([], [IDL.Nat], ['query']),
  'getTradingTransactions' : IDL.Func(
      [],
      [IDL.Vec(TradingTransaction)],
      ['query'],
    ),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getTrendingMemecoins' : IDL.Func([], [IDL.Vec(Memecoin)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWalletConnectionOptions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCEO' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'revokeCEO' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setTradingFeeRate' : IDL.Func([IDL.Nat], [], []),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'trackReferral' : IDL.Func([IDL.Text], [], []),
  'tradeMemecoin' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Principal],
      [],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'withdrawICP' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const OwnershipRecord = IDL.Record({
    'owner' : IDL.Principal,
    'memecoin' : IDL.Text,
    'amount' : IDL.Nat,
    'percentage' : IDL.Nat,
  });
  const Time = IDL.Int;
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const Referral = IDL.Record({
    'referralCode' : IDL.Text,
    'referrer' : IDL.Principal,
    'referredUsers' : IDL.Vec(IDL.Principal),
    'createdAt' : Time,
  });
  const TradingTransaction = IDL.Record({
    'seller' : IDL.Principal,
    'timestamp' : Time,
    'buyer' : IDL.Principal,
    'memecoin' : IDL.Text,
    'price' : IDL.Nat,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
  });
  const Wallet = IDL.Record({
    'balance' : IDL.Nat,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'depositAddress' : IDL.Text,
  });
  const FeeRecord = IDL.Record({
    'user' : IDL.Principal,
    'depositAddress' : IDL.Text,
    'timestamp' : Time,
    'amount' : IDL.Nat,
  });
  const LiquidityLock = IDL.Record({
    'unlockDate' : Time,
    'duration' : IDL.Nat,
    'isLocked' : IDL.Bool,
    'amount' : IDL.Nat,
  });
  const Memecoin = IDL.Record({
    'creator' : IDL.Principal,
    'logo' : ExternalBlob,
    'name' : IDL.Text,
    'createdAt' : Time,
    'liquidityLock' : LiquidityLock,
    'description' : IDL.Text,
    'totalSupply' : IDL.Nat,
    'category' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const TransactionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const TransactionType = IDL.Variant({
    'deposit' : IDL.Null,
    'withdrawal' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'status' : TransactionStatus,
    'transactionType' : TransactionType,
    'destinationAddress' : IDL.Opt(IDL.Text),
    'user' : IDL.Principal,
    'timestamp' : Time,
    'confirmationDetails' : IDL.Opt(IDL.Text),
    'memecoin' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'approveTrade' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createMemecoin' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          ExternalBlob,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'designateCEO' : IDL.Func([IDL.Principal], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'generateReferralLink' : IDL.Func([], [IDL.Text], []),
    'getActorId' : IDL.Func([], [IDL.Text], ['query']),
    'getAllOwnershipRecords' : IDL.Func(
        [],
        [IDL.Vec(OwnershipRecord)],
        ['query'],
      ),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getAllReferrals' : IDL.Func([], [IDL.Vec(Referral)], ['query']),
    'getAllTradingTransactions' : IDL.Func(
        [],
        [IDL.Vec(TradingTransaction)],
        ['query'],
      ),
    'getAvailableCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCEO' : IDL.Func([], [IDL.Text], ['query']),
    'getCEOPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWallet' : IDL.Func([], [IDL.Opt(Wallet)], ['query']),
    'getDepositAddress' : IDL.Func([], [IDL.Text], []),
    'getFeeRecords' : IDL.Func([], [IDL.Vec(FeeRecord)], ['query']),
    'getHotMemecoins' : IDL.Func([], [IDL.Vec(Memecoin)], ['query']),
    'getIcpswapWalletAddress' : IDL.Func([], [IDL.Text], ['query']),
    'getIcpswapWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getIcpswapWalletConnectionStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getLiquidityLocks' : IDL.Func([], [IDL.Vec(LiquidityLock)], ['query']),
    'getMemecoins' : IDL.Func([], [IDL.Vec(Memecoin)], ['query']),
    'getMemecoinsbyCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Memecoin)],
        ['query'],
      ),
    'getNewMemecoins' : IDL.Func([], [IDL.Vec(Memecoin)], ['query']),
    'getOfficialDepositAddresses' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getOfficialTelegram' : IDL.Func([], [IDL.Text], ['query']),
    'getOfficialTwitter' : IDL.Func([], [IDL.Text], ['query']),
    'getOwnershipRecords' : IDL.Func([], [IDL.Vec(OwnershipRecord)], ['query']),
    'getProgressingMemecoins' : IDL.Func([], [IDL.Vec(Memecoin)], ['query']),
    'getReferralCode' : IDL.Func([], [IDL.Text], ['query']),
    'getReferralStats' : IDL.Func([], [IDL.Opt(Referral)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTradingFeeRate' : IDL.Func([], [IDL.Nat], ['query']),
    'getTradingTransactions' : IDL.Func(
        [],
        [IDL.Vec(TradingTransaction)],
        ['query'],
      ),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getTrendingMemecoins' : IDL.Func([], [IDL.Vec(Memecoin)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWalletConnectionOptions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCEO' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'revokeCEO' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setTradingFeeRate' : IDL.Func([IDL.Nat], [], []),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'trackReferral' : IDL.Func([IDL.Text], [], []),
    'tradeMemecoin' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Principal],
        [],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'withdrawICP' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };